version: '3'
services:
  kudu-master:
    container_name: kudu-master
    build:
      context: .
      dockerfile: Dockerfile
    image: comchangs/kudu:latest
    networks:
      default:
        aliases:
        - kudu
    cap_add:
    - SYS_TIME
    ports:
    - 7051:7051
    - 8051:8051
    environment:
      KUDU_MASTER: "true"
  kudu-tserver:
    container_name: kudu-tserver
    build:
      context: .
      dockerfile: Dockerfile
    image: comchangs/kudu:latest
    cap_add:
    - SYS_TIME
    ports:
    - 7050:7050
    - 8050:8050
    environment:
      KUDU_MASTER: "false"
networks:
  default:
    external:
      name: comchangs
  comchangs:
    driver: bridge